package Files;

public class EditPayload {
	

	public static String EditUser(String NAME)
	{
		String payload= "{\r\n"
				+ "    \"hostName\": \"0:0:0:0:0:0:0:1\",\r\n"
				+ "    \"createdBy\": \"pingcust\",\r\n"
				+ "    \"templateId\": \"newz1\",\r\n"
				+ "    \"id\": \""+NAME+"\",\r\n"
				+ "     \"firstName\": \"ravish\",\r\n"
				+ "    \"lastName\": \"kk updated\",\r\n"
				+ "    \"email\": \"jj@kkupdated.com\",\r\n"
				+ "    \"employer\": \"MCKupdated\",\r\n"
				+ "    \"type\": \"E\",\r\n"
				+ "    \"userTemplate\": \"NO\",\r\n"
				+ "    \"applFeatureAccessCds\": \"2-1\",\r\n"
				+ "    \"chkIpInd\": \"NO\",\r\n"
				+ "    \"loginAsOverride\": \"2\",\r\n"
				+ "    \"groups\": [\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"ISMC Owner\",\r\n"
				+ "            \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"Reports and analysis 6.0\",\r\n"
				+ "            \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"SMO Data Exchange\",\r\n"
				+ "            \"action\":\"remove\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"AdminSecurity\",\r\n"
				+ "            \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"RxPak\",\r\n"
				+ "            \"action\":\"remove\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"EnterpriseRx\",\r\n"
				+ "            \"action\":\"add\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "\r\n"
				+ "\"orderingAccounts\": [\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"000007\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"096206\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"000072\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"241654\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"000078\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"553183\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"283044\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"878586\",\r\n"
				+ "             \"action\":\"remove\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "\r\n"
				+ "    \"mcapAccounts\": [\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"000072\",\r\n"
				+ "             \"action\":\"remove\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"000303\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"accountNumber\": \"999999\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "\"rnaAccounts\":    [\r\n"
				+ "    {\r\n"
				+ "        \"accessRoldCd\":\"CID\",\r\n"
				+ "        \"lvl1Value\":\"000048\",\r\n"
				+ "        \"lvl2Value\":\"\",\r\n"
				+ "        \"lvl3Value\":\"\",\r\n"
				+ "        \"lvl4Value\":\"\",\r\n"
				+ "        \"lvl5Value\":\"\",\r\n"
				+ "        \"traceAbilityFlag\":\"YES\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"accessRoldCd\":\"CID\",\r\n"
				+ "        \"lvl1Value\":\"000148\",\r\n"
				+ "        \"lvl2Value\":\"\",\r\n"
				+ "        \"lvl3Value\":\"\",\r\n"
				+ "        \"lvl4Value\":\"\",\r\n"
				+ "        \"lvl5Value\":\"\",\r\n"
				+ "        \"traceAbilityFlag\":\"NO\",\r\n"
				+ "             \"action\":\"remove\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"accessRoldCd\":\"CHN\",\r\n"
				+ "        \"lvl1Value\":\"0350\",\r\n"
				+ "        \"lvl2Value\":\"\",\r\n"
				+ "        \"lvl3Value\":\"\",\r\n"
				+ "        \"lvl4Value\":\"\",\r\n"
				+ "        \"lvl5Value\":\"\",\r\n"
				+ "        \"traceAbilityFlag\":\"YES\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"accessRoldCd\":\"CID\",\r\n"
				+ "        \"lvl1Value\":\"000054\",\r\n"
				+ "        \"lvl2Value\":\"\",\r\n"
				+ "        \"lvl3Value\":\"\",\r\n"
				+ "        \"lvl4Value\":\"\",\r\n"
				+ "        \"lvl5Value\":\"\",\r\n"
				+ "        \"traceAbilityFlag\":\"NO\",\r\n"
				+ "             \"action\":\"add\"\r\n"
				+ "    }\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ "    \"identityData\": {\r\n"
				+ "        \"cust_typ_cd\": \"31\",\r\n"
				+ "    \r\n"
				+ "        \"sgmnt_cd\": \"31\",\r\n"
				+ "        \"sgmnt_role_cd\": \"31-2\"\r\n"
				+ "    },\r\n"
				+ "    \"locationData\": {\r\n"
				+ "        \"dc_ids\": \"8130,8581,8955\",\r\n"
				+ "        \"dc_dlvry_rte_stop_hier\": \"8106,8106-016-016,8106-016\",\r\n"
				+ "        \"dc_terr_hier\": \"8106-0011\",\r\n"
				+ "        \"acct_st_cds\": \"CA,IN,NH\",\r\n"
				+ "        \"acct_zip_cds\": \"11111,22221,12345\"\r\n"
				+ "    },\r\n"
				+ "    \"membershipData\": {\r\n"
				+ "        \"natl_grp_hier\": \"0230-000500-000004-000001,0230-000500-000004-000002\",\r\n"
				+ "        \"chn_cds\": \"322,047,\",\r\n"
				+ "  \r\n"
				+ "        \"adhoc_grp_cds\": \"144,314,103\",\r\n"
				+ "        \"pgm_mbrsh_cds\": \"pgm_012,pgm_07,pgm_060\"\r\n"
				+ "    },\r\n"
				+ "    \"otherData\": {\r\n"
				+ "        \"rna_name\": \"APCI\",\r\n"
			
				+ "\r\n"
				+ "        \"hq_access_ind\": \"NO\",\r\n"
				+ "        \"mod_prfl_ind\": \"YES\",\r\n"
				+ "        \"password_mod_flag\": \"NO\",\r\n"
				+ "        \"force_e_mail_update_flag\": \"NO\",\r\n"
				+ "        \"prfr_rply_meth_cd\": \"03\",\r\n"
				+ "        \"mfg_type\": \"Brand\"\r\n"
				+ "    },\r\n"
				+ "    \"ipRange\": [\r\n"
				+ "        {\r\n"
				+ "            \"startIp\": \"10.10.10.10\",\r\n"
				+ "            \"stopIp\": \"10.10.10.25\",\r\n"
				+ "            \"action\": \"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"startIp\": \"192.168.6.1\",\r\n"
				+ "            \"stopIp\": \"192.168.6.100\",\r\n"
				+ "            \"action\": \"remove\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"rnaFunctionCodes\": [\r\n"
				+ "        {\r\n"
				+ "            \"functionCode\": \"3\",\r\n"
				+ "            \"action\": \"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"functionCode\": \"5\",\r\n"
				+ "            \"action\": \"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"functionCode\": \"6\",\r\n"
				+ "            \"action\": \"add\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"functionCode\": \"2\",\r\n"
				+ "            \"action\": \"remove\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
	
	
		return payload;
	}
	

}
